### ISSUE TITLE
`requirements.txt`

### ISSUE THREAD

**Issue by landmann** [XPixelGroup/DiffBIR#1]
Thanks for this work! Now, I'm getting a strange error where it's telling me `ModuleNotFoundError: No module named 'pytorch_lightning.utilities.distributed'` but I already have `pytorch-lightning==1.8.5.post0`. Any idea?

Here's the full stack trace

```
Traceback (most recent call last):
  File "/content/diffbir/inference.py", line 15, in <module>
Sep 02 at 22:50:30.984
    from model.cldm import ControlLDM
  File "/content/diffbir/model/cldm.py", line 18, in <module>
Sep 02 at 22:50:30.984
    from ldm.models.diffusion.ddpm import LatentDiffusion
  File "/content/diffbir/ldm/models/diffusion/ddpm.py", line 20, in <module>
Sep 02 at 22:50:30.985
    from pytorch_lightning.utilities.distributed import rank_zero_only
Sep 02 at 22:50:30.985
ModuleNotFoundError: No module named 'pytorch_lightning.utilities.distributed'
```

**Comment by 0x3f3f3f3fun** [comment]
Thanks for your question, you can downgrade your pytorch_lightning to version 1.4.2.

**Comment by landmann** [comment]
What about the rest of the packages? I'm now getting this

```
    from torchmetrics.utilities.data import get_num_classes as _get_num_classes
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (/usr/local/lib/python3.9/site-packages/torchmetrics/utilities/data.py)
```

**Comment by joreeves** [comment]
@landmann I fixed this by uninstalling torchmetrics then `pip install torchmetrics==0.6.0`

**Comment by 0x3f3f3f3fun** [comment]
Thanks for your question! I will provide a requirements.txt file immediately.

发件人：Josiah Reeves ***@***.***>
发送日期：2023-09-05 11:09:09
收件人：XPixelGroup/DiffBIR ***@***.***>
抄送人：0x3f3f3f3fun ***@***.***>,Mention ***@***.***>
主题：Re: [XPixelGroup/DiffBIR] `requirements.txt` (Issue #1)

@landmann I fixed this by uninstalling torchmetrics then pip install torchmetrics==0.6.0

**Comment by 0x3f3f3f3fun** [comment]
I will provide a requirements.txt file immediately. 😄
