### ISSUE TITLE
the resolution and classes of imagenet dataset

### ISSUE THREAD

**Issue by YilanWang** [XPixelGroup/DiffBIR#100]
I found that in DiffBIR, the resolution of imagenet data is set to 512x512, but as far as I know, the resolution of imagenet is 256x256. And I have another question, which classes of image net do you choose? image1k or 11k? Thank you very much

**Comment by 0x3f3f3f3fun** [comment]
1. We use center crop to generate GT with a resolution of 512.
2. ImageNet-1k, about 1.3M training images.

**Comment by YilanWang** [comment]
thanks for reply! I have reproduced the results. I close this issue
