### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by happy-liuzhixuan** [XPixelGroup/DiffBIR#135]
您好，请问模型的V1和V2版本有什么区别

**Comment by 0x3f3f3f3fun** [comment]
v2是用新的数据训练的。相比于v1，v2在训练时为每一个图像添加了文本描述。但是这个数据处理的不够好，所以效果上没有明显提升。欢迎您试试v2.1。

**Comment by happy-liuzhixuan** [comment]
谢谢，我接下来尝试一下您最新提供的v2.1，期待更好的结果
