### ISSUE TITLE
Need Help WIth Gradio Demo

### ISSUE THREAD

**Issue by MarsEverythingTech** [XPixelGroup/DiffBIR#139]
Hello,

I recently installed the latest update on my PC. I have RTX 3070 Ti 8GB VRAM. I am having a hard time using the Gradio Demo locally on my PC. It is taking a long time to upscale the face. I checked every checkbox with "tiled", and leaving the default values. Any suggestions on how to process faster?

Thanks in advance.

**Comment by happy-liuzhixuan** [comment]
同遇到这种问题，希望可以提供建议，感谢

**Comment by 0x3f3f3f3fun** [comment]
Thank you for your feedback!

Can you tell me what tile size you've set? I guess that the tile size might be too small, which is why it's taking a long time. Currently, the default captioner used by the Gradio script is LLAVA 8bit, which consumes a considerable amount of VRAM. For users with 8GB VRAM, I recommend setting the captioner to RAM, allowing for a larger tile size. Alternatively, you can set the captioner to none and manually add image description information in the positive prompt text box.

**Comment by MarsEverythingTech** [comment]
> Thank you for your feedback!
> 
> Can you tell me what tile size you've set? I guess that the tile size might be too small, which is why it's taking a long time. Currently, the default captioner used by the Gradio script is LLAVA 8bit, which consumes a considerable amount of VRAM. For users with 8GB VRAM, I recommend setting the captioner to RAM, allowing for a larger tile size. Alternatively, you can set the captioner to none and manually add image description information in the positive prompt text box.

Here are the screenshots of the settings I am using. Could you please let me know what to change?

![Screenshot 2024-11-29 005339](https://github.com/user-attachments/assets/5c257a3c-5bca-4a35-8706-0cf48e79787a)
![Screenshot 2024-11-29 005438](https://github.com/user-attachments/assets/298cf6b2-bae7-43fb-a683-a1373ae15d97)
![Screenshot 2024-11-29 005516](https://github.com/user-attachments/assets/379657d2-ff2a-462a-be4d-6cc72e0ef83a)

Thanks in advance.

**Comment by 0x3f3f3f3fun** [comment]
1. change the [parameter](https://github.com/XPixelGroup/DiffBIR/blob/1cf77e2e815ceedb723d5bc990f31985b6d80a93/run_gradio.py#L41) in gradio script.
```python
# Set captioner to llava or ram to enable auto-caption
# captioner = "llava"
captioner = "ram" # or "none"
```
2. Set classifier-free guidance scale to 8, it will produces more details
3. try to enlarge your tile size

I will incorporate these changes into Gradio. Thank you for your feedback. If it's still taking a long time, you can take a screenshot and show me which stage you're stuck at.

**Comment by 0x3f3f3f3fun** [comment]
Sorry, I currently don't have access to a GPU with 8GB VRAM for testing. You can try increasing tile size, and if the gradio doesn't return an error, then it should be fine. Another reason for the long processing time is that I have set the tile stride in the program to be fixed at half the tile size, which is unnecessary for cleaner. I will fix this issue as soon as possible.
