### ISSUE TITLE
inference result full of noise

### ISSUE THREAD

**Issue by mumu-code** [XPixelGroup/DiffBIR#141]
![QQ20241202-193123](https://github.com/user-attachments/assets/9bee39ec-bd1c-4475-8f22-f9cda58be87d)
Great job! But when I finish the env requirments and try to inference the demo pictures ,I find my results is full of noise like above,So how to resolve this problem

**Comment by mumu-code** [comment]
already fixed

**Comment by 0x3f3f3f3fun** [comment]
Thanks for your feedback.

**Comment by happy-liuzhixuan** [comment]
我自己训练出的模型测试也是这种情况，如何解决
