### ISSUE TITLE
如何加载本地已下载的权重？how to load locally downloaded weights？

### ISSUE THREAD

**Issue by SkywalkerSZW** [XPixelGroup/DiffBIR#147]
如何加载本地已下载的权重，由于防火墙无法访问huggingface，我通过VPN下载了权重，如何在代码中进行加载？
Due to the firewall, I cannot access Hugging Face directly. I used a VPN to download the weights. How can I load them in the code?

**Comment by 0x3f3f3f3fun** [comment]
Create a directory `weights` and put the weight into it.

**Comment by 0x3f3f3f3fun** [comment]
By the way, you can set `--captioner none` to avoid downloading LLaVA or RAM from hugging face.

**Comment by SkywalkerSZW** [comment]
Thanks a lot, it works for me to add "export HF_ENDPOINT=https://hf-mirror.com" before the inference command.

**Comment by 0x3f3f3f3fun** [comment]
Wow! This is great!
