### ISSUE TITLE
PretrainedModels能否上传到modelscope

### ISSUE THREAD

**Issue by libhot** [XPixelGroup/DiffBIR#18]
鉴于国内封禁了huggingface，能否将PretrainedModels上传到modelscope
https://www.modelscope.cn

**Comment by 0x3f3f3f3fun** [comment]
好的，我会尽快上传并通知你

**Comment by 0x3f3f3f3fun** [comment]
你好！我发现上传model scope有一些麻烦（网速太慢），所以我先将模型上传到了百度云盘，你可以在README中找到链接 😄，模型比较大，希望你不会受到网速的困扰~
