### ISSUE TITLE
Problem with Pytorch Lightning

### ISSUE THREAD

**Issue by wdsongama** [XPixelGroup/DiffBIR#2]
Traceback (most recent call last):
  File "C:\Users\wdson\Downloads\Compressed\DiffBIR-main\inference.py", line 15, in <module>
    from model.cldm import ControlLDM
  File "C:\Users\wdson\Downloads\Compressed\DiffBIR-main\model\cldm.py", line 18, in <module>
    from ldm.models.diffusion.ddpm import LatentDiffusion
  File "C:\Users\wdson\Downloads\Compressed\DiffBIR-main\ldm\models\diffusion\ddpm.py", line 20, in <module>
    from pytorch_lightning.utilities.distributed import rank_zero_only
ModuleNotFoundError: No module named 'pytorch_lightning.utilities.distributed'

I am getting this error, even though I have Pytorch Lightning installed. Also, I could not find "requirements.txt" in the repository, so I installed the modules as they were being required.

**Comment by landmann** [comment]
Haha I commented the same thing and having the same problem. 
_https://github.com/XPixelGroup/DiffBIR/issues/1_

**Comment by 0x3f3f3f3fun** [comment]
I have provided a version (1.4.2) for PyTorch Lightning in `install_env.sh`. Now I think it's necessary to provide a standardized `requirements.txt` for users. Thanks for your question! 😄

**Comment by wdsongama** [comment]
I wasn't being able to ru install_env.sh because I had copied the full command on the repo, but when I typed just the file name, it ran normally. Sorry for the inconvenience.

**Comment by moonsun153** [comment]
Could not find module 'E:\DiffBIR\diffbirenvs\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "E:\DiffBIR\gradio_diffbir.py", line 8, in <module>
    import pytorch_lightning as pl
  File "E:\DiffBIR\diffbirenvs\lib\site-packages\pytorch_lightning\__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "E:\DiffBIR\diffbirenvs\lib\site-packages\pytorch_lightning\metrics\__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "E:\DiffBIR\diffbirenvs\lib\site-packages\pytorch_lightning\metrics\classification\__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "E:\DiffBIR\diffbirenvs\lib\site-packages\pytorch_lightning\metrics\classification\accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics, void
  File "E:\DiffBIR\diffbirenvs\lib\site-packages\pytorch_lightning\metrics\utils.py", line 22, in <module>
    from torchmetrics.utilities.data import get_num_classes as _get_num_classes
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (E:\DiffBIR\diffbirenvs\lib\site-packages\torchmetrics\utilities\data.py)，
How can I fix this error?

**Comment by 0x3f3f3f3fun** [comment]
> Could not find module 'E:\DiffBIR\diffbirenvs\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax. warn(f"Failed to load image Python extension: {e}") Traceback (most recent call last): File "E:\DiffBIR\gradio_diffbir.py", line 8, in import pytorch_lightning as pl File "E:\DiffBIR\diffbirenvs\lib\site-packages\pytorch_lightning__init__.py", line 20, in from pytorch_lightning import metrics # noqa: E402 File "E:\DiffBIR\diffbirenvs\lib\site-packages\pytorch_lightning\metrics__init__.py", line 15, in from pytorch_lightning.metrics.classification import ( # noqa: F401 File "E:\DiffBIR\diffbirenvs\lib\site-packages\pytorch_lightning\metrics\classification__init__.py", line 14, in from pytorch_lightning.metrics.classification.accuracy import Accuracy # noqa: F401 File "E:\DiffBIR\diffbirenvs\lib\site-packages\pytorch_lightning\metrics\classification\accuracy.py", line 18, in from pytorch_lightning.metrics.utils import deprecated_metrics, void File "E:\DiffBIR\diffbirenvs\lib\site-packages\pytorch_lightning\metrics\utils.py", line 22, in from torchmetrics.utilities.data import get_num_classes as _get_num_classes ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (E:\DiffBIR\diffbirenvs\lib\site-packages\torchmetrics\utilities\data.py)， How can I fix this error?

Try `pip install torchmetrics==0.6.0`
