### ISSUE TITLE
Issue when try to train model

### ISSUE THREAD

**Issue by NgdHung31** [XPixelGroup/DiffBIR#23]
I have done the split creating the list train.list and val.list. I also edited the config files according to the instructions in the readme.md but I got an error, it seemed like there was a problem reading the image data so I checked again but couldn't find any problems. Can you help me ?

![Screenshot from 2023-09-11 15-21-54](https://github.com/XPixelGroup/DiffBIR/assets/83905082/b19a9d43-670f-4afe-8005-1ed5f00047ca)

**Comment by NgdHung31** [comment]
here is my config file
![image](https://github.com/XPixelGroup/DiffBIR/assets/83905082/279efeb7-d15d-47e7-b6e3-16bd9488717e)

**Comment by 0x3f3f3f3fun** [comment]
I am glad to help you 😄. Can you show me the training file list?

**Comment by 0x3f3f3f3fun** [comment]
What about your batch_size? If the batch size is larger than the size of training set and `drop_last` option is specified, the dataloader won't return any batch.

**Comment by NgdHung31** [comment]
Great, I reduced the batch_size and val_check_interval and it worked. Thank you very much

**Comment by weiruihhh** [comment]
Good question and prefect answer
