### ISSUE TITLE
RuntimeError: User specified an unsupported autocast device_type 'cuda:0'

### ISSUE THREAD

**Issue by Nikoos** [XPixelGroup/DiffBIR#26]
Hello Team,

When trying to run the following command : `python inference.py --config configs/model/cldm.yaml --ckpt weights/general_full_v1.ckpt --steps 50 --sr_scale 1 --image_size 512 --input results/maxout/ --color_fix_type wavelet --resize_back --output results/detailed/ --disable_preprocess_model --device cuda` on Linux Docker container (with a AMD 7900XT), I have the following error : 

`RuntimeError: User specified an unsupported autocast device_type 'cuda:0'`

Before commit 30355a1284496f557e8492da3bbbdd0f539a3963 I was able to perform some image restoration, once pulled latest commit, I got the given error.

Best regards,

Nikos

**Comment by 0x3f3f3f3fun** [comment]
Hello! Thanks for your feedback! We can reproduce this bug through turning off xformers while using CUDA. We have fixed this issue in the latest commit, you can have a try😄. Please feel free to contact us if you have any further questions.

**Comment by Nikoos** [comment]
Hello @0x3f3f3f3fun ,

I was able to test the same command, it works. I will close this issue.

Thanks for your help and your hard work.

Nikos
