### ISSUE TITLE
about  test  error

### ISSUE THREAD

**Issue by zhanghongyong123456** [XPixelGroup/DiffBIR#3]
![image](https://github.com/XPixelGroup/DiffBIR/assets/48466610/2c1aefd1-8e68-44b7-ba47-d81cef7e5611)

**Comment by 0x3f3f3f3fun** [comment]
Thanks for your question!
- **PytorchStreamReader failed reading zip archive failed finding central directory**
    I find the root casse for this error in [stackoverflow](https://stackoverflow.com/questions/71617570/pytorchstreamreader-failed-reading-zip-archive-failed-finding-central-directory). It seems like you haven't correctly downloaded the model weights for LPIPS. Considering that the weights is automatically downloaded from torchvision, you can try to delete the downloaded weights (~/.cache/torch/hub/checkpoints/alexnet-owt-7be5be79.pth in my machine) and run the script again. I hope this solution is helpful for you. 😄

- **The command "python gradio_diffbir.py ... --swinir_ckpt face_swinir_v1.ckpt"**
    This command is correct. However, it's unnecessary to reload swinir since the `face_swinir_v1.ckpt` is already intergrated in `face_full_v1.ckpt`. The `reload_swinir` is only used when you are attempting to replace the first stage model with another one.
