### ISSUE TITLE
No matching distribution found for triton

### ISSUE THREAD

**Issue by ZXCMiller** [XPixelGroup/DiffBIR#31]
![微信截图_20230912233812](https://github.com/XPixelGroup/DiffBIR/assets/141479314/f3dfff14-6f50-48a8-a24a-6bd8d7719344)
I'm sorry. I don't know what to do.

**Comment by treksis** [comment]
https://github.com/openai/triton#compatibility

Triton does not natively support Windows. 

The solution is to install WSL 2 on your windows.

![image](https://github.com/XPixelGroup/DiffBIR/assets/54779707/d2511443-690a-4053-92d2-0156688c9bcd)

![image](https://github.com/XPixelGroup/DiffBIR/assets/54779707/3e8e34ca-20e2-48a6-a1e7-a65ae4e37065)

Then install python that you want.

After

```
git clone https://github.com/XPixelGroup/DiffBIR.git

python3 -m venv venv

source venv/bin/activate

pip install -r requirements.txt
```
Or, try this instead https://github.com/bycloud-AI/DiffBIR-Windows/

This guy wrote a tutorial. https://www.youtube.com/watch?v=rGnrpxWjBOg

**Comment by 0x3f3f3f3fun** [comment]
@treksis Thank you for your patient response😄.
