### ISSUE TITLE
finetune stable diffusion

### ISSUE THREAD

**Issue by xuanxu92** [XPixelGroup/DiffBIR#38]
Hi, thanks for this excellent work. I am working my own dataset (medical images) now. I see the paper and find the stable diffusion is frozen and also the autoencoder. could you please share the finetuning stable diffusion code if possible?
thanks a lot for your time

**Comment by 0x3f3f3f3fun** [comment]
Thanks for your question! The Stable Diffusion is not finetuned in DiffBIR for maintaining its generative capability, please refer to the official repo of [latent diffusion model](https://github.com/CompVis/stable-diffusion) for finetuning. By the way, Stable Diffusion is not pretrained for generating medical images, which may bring you some trouble.

**Comment by xuanxu92** [comment]
thanks a lot for your help!
