### ISSUE TITLE
Question about video memory consumption, and computational resource requirements

### ISSUE THREAD

**Issue by ARTUROSING** [XPixelGroup/DiffBIR#4]
There is a similar work StableSR, which also uses the Stable Diffusion base model, and its GPU memory requirements are huge. And sometimes even tiling does not save the situation in any way.

StableSR is not able to properly process images with resolution higher than 190px, I personally tried it with different data and parameters, and it's just a huge waste of time.

How much more accessible would your work be to most graphics gas pedals, like those with 8 or 16gb of video memory? 

Thank you very much, for your attention.

**Comment by 0x3f3f3f3fun** [comment]
Thanks for your question!
- **The GPU memory requirements.**
    I conducted a simple test. Running gradio_diffbir.py and restoring an image of 640x640 (sr_scale=1) requires 11GB of GPU memory. Since DiffBIR is based on stable diffusion, it consumes a significant amount of GPU memory. I will consider incorporating some runtime tricks to reduce GPU memory usage, such as transferring unnecessary variables/parameters to the CPU during inference.

- **StableSR is not able to properly process images with resolution higher than 190px.**
    Are you doing x4 SR task? If so, I think both StableSR and our DiffBIR can handle images with a resolution of 760px. If the results of DiffBIR are also unsatisfactory, could you please send a few test images to linxinqi@tju.edu.cn? I'll assist you in testing them.

**Comment by landmann** [comment]
Agreed! This is the best upscaler/enhancer I've used so far, but it's very memory intensive and takes a very long time, sadly!

**Comment by IceClear** [comment]
@ARTUROSING Hi, thanks for your interest of both StableSR and DiffBIR. Would you mind also sending the failure cases to us at [iceclearwjy@gmail.com](mailto:iceclearwjy@gmail.com)? We will have a test to see the problems. Thanks a lot for your valuable feedback on our approach :)
