### ISSUE TITLE
How to change the "Control Strength" in the Code instead of Page?

### ISSUE THREAD

**Issue by SongYxing** [XPixelGroup/DiffBIR#42]

**Comment by SongYxing** [comment]
And why "Checkpoints of SwinIR will be used in training stage2 model" ? The ckpt of SwinIR in the stage2 should be fixed. Loading this ckpt may increase the time consumption and GPU memory in the training stage. Can stage2 training completely offline?

**Comment by 0x3f3f3f3fun** [comment]
Thanks for your questions!
1. modify the input parameter `strength` in inference.py, line 186.
2. SwinIR is fixed during the training of stage2 model, it may not consume much GPU memory and time.
3. You can generate some lq-hq pairs offline for training stage2 model, that is, generate some lq images first ang then apply stage1 model on them to get the smoothed lq as the model inputs.

**Comment by SongYxing** [comment]
Thank you for your patient answer.
The third point of your answer is exactly what I would like to implement now. But the "readme.md" mentions that stage2 of training requires the Swinir ckpt. How to only use I_{reg} to train stage2?

_python scripts/make_stage2_init_weight.py \
--cldm_config configs/model/cldm.yaml \
--sd_weight [sd_v2.1_ckpt_path] \
--**swinir_weight [swinir_ckpt_path]** \
--output [init_weight_output_path]_

**Comment by 0x3f3f3f3fun** [comment]
Take the following steps:
1. create a simple dataset class to load the offline-generated lq and hq images, and be careful about the value range of output tensors, lq should range in [0, 1] and gt should range in [-1, 1].
2. use the identity batch transform.
3. delete the code locate in model/cldm.py, line 338 to disable the preprocess model.

If you want to remove the preprocess model in ControlLDM class, you can delete the code related to preprocess model in model/cldm.py and remove the pretrained swinir weights in scripts/make_stage2_init_weight.py. Please feel free to contact us if you have any further questions!

**Comment by 0x3f3f3f3fun** [comment]
The data flow of our code is: dataset -> dataloader -> batch_transform (work in GPU) -> ControlLDM.get_input

**Comment by SongYxing** [comment]
Thanks for your great work. I will follow your steps to try training without pretrain ckpt.

**Comment by SongYxing** [comment]
Is it possible to add an image clip to ldm?
