### ISSUE TITLE
CUDA out of memory RTX 3060 12GB

### ISSUE THREAD

**Issue by ms-Ana** [XPixelGroup/DiffBIR#43]
The xformers are installed and run correctly. Please, provide configuration with which it can run with 10GB GPU.

**Comment by 0x3f3f3f3fun** [comment]
For 10GB GPU, you can run DiffBIR on a resolution of 512, and use the tile mode for larger images. The GPU memory usage will continue to be optimized and thanks for your insterest on DiffBIR! 😄

**Comment by ms-Ana** [comment]
Thank you

**Comment by AIrtistry** [comment]
> For 10GB GPU, you can run DiffBIR on a resolution of 512, and use the tile mode for larger images. The GPU memory usage will continue to be optimized and thanks for your insterest on DiffBIR! 😄

Hi, DiffBIR is not compatible with videos right ?

**Comment by ms-Ana** [comment]
What do you mean? I use a directory with images, but I assume that you can iterate over video frames with video input, or split video into frames with ffmpeg and then provide a directory with images.
