### ISSUE TITLE
about urls for RealESRGAN checkpoint

### ISSUE THREAD

**Issue by MasahideOkada** [XPixelGroup/DiffBIR#47]
line [326](https://github.com/XPixelGroup/DiffBIR/blob/main/utils/realesrgan/realesrganer.py#L326) in realesrganer.py is 
```py
model_path=f"https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x{scale}plus.pth",
```
when `scale == 2`, it tries to download `RealESRGAN_x2plus.pth` from v0.1.0, but v0.1.0 doesn't have x2plus checkpoint.
It should be download from v0.2.1

**Comment by ziyannchen** [comment]
I've fixed this! Thx for the useful comments!
