### ISSUE TITLE
谢谢作者回复，是我理解错了

### ISSUE THREAD

**Issue by GuitarZH** [XPixelGroup/DiffBIR#58]

**Comment by GuitarZH** [comment]
紧跟着刚才的提问，还有1个基础问题想请教您。
当使用以上脚本后，测试结果与标签有色差，请问是我哪里设置不合理吗？

**Comment by 0x3f3f3f3fun** [comment]
你好。
1. sr_scale设置为4是因为我们的baseline (e.g. RealESRGAN)都是4倍放大，所以我们对齐他们选择了4倍。
2. 在采用wavelet colorfix的情况下我们还没有碰到过色偏问题，能否将测试用例发送到linxinqi@tju.edu.cn呢？

**Comment by ziyannchen** [comment]
哈喽，感谢提问。问题可以不用修改哈，issue保留方便其他有问题的用户参考～

**Comment by GuitarZH** [comment]
> 哈喽，感谢提问。问题可以不用修改哈，issue保留方便其他有问题的用户参考～

好的，我这就恢复。
