### ISSUE TITLE
🦒 colab

### ISSUE THREAD

**Issue by camenduru** [XPixelGroup/DiffBIR#6]
Thanks for the project ❤️ I made a colab. 🥳 I hope you like it. https://github.com/camenduru/DiffBIR-colab

**Comment by 0x3f3f3f3fun** [comment]
Thank you very much! I will update your Colab to the README in the next commit. Recently I've been busy with the start of the school year, so I haven't had much time to further improve DiffBIR. Thanks for your help! ❤️

**Comment by Phhofm** [comment]
Thanks for the colab, I wanted to test it out but this colab seems to crash because its running out of RAM if I saw this correctly:
![image](https://github.com/XPixelGroup/DiffBIR/assets/14755670/2428e48b-c8db-484e-b0c6-dee4bf296ef5)

So would only Colab Pro users be able to run this? This would limit its usefullness since I assume most people coming to this repo wanting to try DiffBIR out wont have Pro and just experience the colab not working / crashing.
Is there maybe a way to run DiffBIR in colab to use less RAM so it wont crash for non-paying users?

**Comment by 0x3f3f3f3fun** [comment]
> Thanks for the colab, I wanted to test it out but this colab seems to crash because its running out of RAM if I saw this correctly: ![image](https://user-images.githubusercontent.com/14755670/266231901-2428e48b-c8db-484e-b0c6-dee4bf296ef5.png)
> 
> So would only Colab Pro users be able to run this? This would limit its usefullness since I assume most people coming to this repo wanting to try DiffBIR out wont have Pro and just experience the colab not working / crashing. Is there maybe a way to run DiffBIR in colab to use less RAM so it wont crash for non-paying users?

Thanks for your suggestions 😄. I think the only solution to this problem is to reduce the memory usage of DiffBIR. And we will do that as soon as possible!

**Comment by c4fun** [comment]
As a colab pro user, I also encounter RAM problem on the second or third image.

Perhaps we could check for mem leaks?

**Comment by treksis** [comment]
We need update

```
Status Legend:
(OK):download completed.
2023-09-12 21:44:00.642756: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/DiffBIR/gradio_diffbir.py", line 15, in <module>
    from model.cldm import ControlLDM
  File "/content/DiffBIR/model/cldm.py", line 18, in <module>
    from ldm.models.diffusion.ddpm import LatentDiffusion
  File "/content/DiffBIR/ldm/models/diffusion/ddpm.py", line 20, in <module>
    from pytorch_lightning.utilities.distributed import rank_zero_only
ModuleNotFoundError: No module named 'pytorch_lightning.utilities.distributed'
```

**Comment by asanakoy** [comment]
> We need update
> 
> ```
> Status Legend:
> (OK):download completed.
> 2023-09-12 21:44:00.642756: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
> Traceback (most recent call last):
>   File "/content/DiffBIR/gradio_diffbir.py", line 15, in <module>
>     from model.cldm import ControlLDM
>   File "/content/DiffBIR/model/cldm.py", line 18, in <module>
>     from ldm.models.diffusion.ddpm import LatentDiffusion
>   File "/content/DiffBIR/ldm/models/diffusion/ddpm.py", line 20, in <module>
>     from pytorch_lightning.utilities.distributed import rank_zero_only
> ModuleNotFoundError: No module named 'pytorch_lightning.utilities.distributed'
> ```

This is because of the `pytorch_lightning.utilities.distributed`was removed in the latest pytorch_lightning

**Comment by camenduru** [comment]
Please use this link for reporting colab-related issues:  https://github.com/camenduru/DiffBIR-colab/issues
