### ISSUE TITLE
Torch not compiled with CUDA enabled in MacOS

### ISSUE THREAD

**Issue by Sonamea** [XPixelGroup/DiffBIR#60]
你好，我装好之后快速启动时提示AssertionError: Torch not compiled with CUDA enabled，网上一些说是torch版本的原因，但是我在torch主页上看到只有一个版本适合mac，重新安装了还是这个错误，麻烦解答下，谢谢。我的macOS版本是Sonama14 X64。

**Comment by ziyannchen** [comment]
我们目前没有支持Mac+CUDA。根据我们的了解，目前Mac的新设备显卡不是nvidia的了，对CUDA不兼容。
如果是M1的版本，可以直接用mps加速哈，我们在[文档](https://github.com/XPixelGroup/DiffBIR/blob/main/assets/docs/installation_xOS.md)里边已经写了教程。

**Comment by Sonamea** [comment]
谢谢！
