### ISSUE TITLE
训练时UNet参数freeze问题

### ISSUE THREAD

**Issue by yimingz1218** [XPixelGroup/DiffBIR#63]
您好，我按照您的代码做训练的过程中发现似乎UNet (Diffusion Wrapper)的参数并没有freeze住，和paper中写的不是很一样。想问一下是否是训练的代码有bug，可以简单的在ddpm的母类那里将UNet的梯度freeze住吗？

**Comment by EternalEvan** [comment]
应该是锁住的，有个sd_lock

**Comment by yimingz1218** [comment]
> 应该是锁住的，有个sd_lock

嗯嗯对的，我之前的理解有错误。

训练controlnet的时候，UNet的梯度是不能锁的，只是这个参数没有喂给优化器，所以训练过程不会去优化本身的stable diffusion。
但是对于放开UNet梯度导致的显存占用大的问题，目前看到diffusers的方法是最好的，就是说把cnet的输入变成resnet的输出。也有一个简单粗暴的方法就是直接把input的require_grad放开，然后锁住UNet的权重。

**Comment by Brandon-git-hub** [comment]
"也有一个简单粗暴的方法就是直接把input的require_grad放开，然后锁住UNet的权重。" 這想法超有意思的!!! 請問您現在是這麼做的嗎?
