### ISSUE TITLE
Does DiffBIR support input at arbitrary resolutions?

### ISSUE THREAD

**Issue by IDKiro** [XPixelGroup/DiffBIR#7]
Excellent work, but I noticed while reading the paper and code that it seems to not support arbitrary resolution input (instead, it forcibly scales the image). This feature is supported in both PatchDM and StableSR.

If it indeed doesn't support large image restoration, are there plans to include this feature?

**Comment by 0x3f3f3f3fun** [comment]
For images smaller than 512, we resize them to a resolution of 512 and then perform restoration. For images larger than 512, we directly use them as input to DiffBIR, relying on DiffBIR's generalization ability for restoration. However, this approach imposes significant demands on GPU memory😢😢😢 , so we do indeed require a patch-based restoration method. Currently, our primary focus is on improving the restoration performance of DiffBIR at a resolution around 512, so it may be some time before we incorporate a patch-based sampling strategy.

**Comment by IDKiro** [comment]
Thank you very much for your answer. If possible, please notify me once it's implemented.

Thanks again for your outstanding work.

**Comment by IDKiro** [comment]
Excellent work; although I've already implemented a similar feature myself, what you offer is more powerful. I will try to integrate it into my code.
Thank you very much for your work!
