### ISSUE TITLE
请问如何在严格的离线实验环境进行模型部署

### ISSUE THREAD

**Issue by liulipeng0538** [XPixelGroup/DiffBIR#81]
想测试人脸增强项目，运行inference_face.py后，离线环境中报错提示需下载文件，报错提示如下，请问如何解决，多谢：'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 91e8a70f-bbcd-4911-8c3d-dd5665f7ac96)')' thrown while requesting HEAD https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/resolve/main/open_clip_pytorch_model.bin

**Comment by ziyannchen** [comment]
这是脚本正在自动从hugging face下载CLIP模型文件。仅当模型文件缺失时，才会进行自动下载。
所以建议先从在线环境下载模型，然后想办法把这些文件离线传输到实验环境对应的文件夹中。之后再运行脚本不会再自动进行模型下载。


1、你可以选择从在线环境中直接运行inference_face.py脚本，确保你的网络能正常访问huggingface，脚本将自动下载所有的模型；（非DiffBIR模型将被自动下载到`~/.cache/huggingface/hub/`文件夹中，你只需要复制这个文件夹即可）
2、也可以根据下面的下载链接来进行手动下载。

模型对应的文件夹在下面的checklist说明。
所有你需要下载的模型文件: 
- 下载[open_clip_pytorch_model.bin](https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/resolve/main/open_clip_pytorch_model.bin)至文件夹`~/.cache/huggingface/hub/`(这是脚本自动下载的文件夹地址，你也可以选择其他文件夹)，并在`configs/model/cldm.yaml`中添加一条模型指定语句：
```
84 cond_stage_config:
85    target: ldm.modules.encoders.modules.FrozenOpenCLIPEmbedder
86    params:
+       version: "${HOME}/.cache/huggingface/hub/open_clip_pytorch_model.bin"
87      freeze: True
88      layer: "penultimate"
```
- 下载[alexnet-owt-7be5be79.pth](https://download.pytorch.org/models/alexnet-owt-7be5be79.pth)到文件夹`~/.cache/torch/hub/checkpoints`中；
- 下载项目主页的DiffBIR的人脸模型[face_full_v1.ckpt](https://huggingface.co/lxq007/DiffBIR/resolve/main/face_full_v1.ckpt)到文件夹`weights/`下；
- 如果你需要使用背景增强功能，请下载项目主页DiffBIR [general_full_v1.ckpt](https://huggingface.co/lxq007/DiffBIR/resolve/main/general_full_v1.ckpt)、[general_swinir_v1.ckpt](https://huggingface.co/lxq007/DiffBIR/resolve/main/general_swinir_v1.ckpt)放到weights/文件夹下(如果你想使用RealESRGAN作为background upsampler, 请下载[RealESRGANx2](https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth)/[x4](https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth)模型到`weights/realesrgan/`文件夹下);

（其中DiffBIR有关的模型文件提供了huggingface的下载链接，你还可以从主页中找到百度云以及openxlab的国内云服务器的下载链接。）
