### ISSUE TITLE
TypeError: sample() missing 2 required positional arguments: 'positive_prompt' and 'negative_prompt'

### ISSUE THREAD

**Issue by shiyuan7** [XPixelGroup/DiffBIR#89]
The "sample" parameter on line 394 in ./model/cldm.py does not seem to match the definition on line 499 in ./model/spaced_sampler.py.

**Comment by fengza** [comment]
I met the same problem, is your problem solved? @shiyuan7

**Comment by 0x3f3f3f3fun** [comment]
Please refer to #55 . I will fix this issue as soon as possible.

**Comment by shiyuan7** [comment]
Thank you very much for your reply!
